### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'exceptions.IOError' objects

### ISSUE THREAD

**Issue by geziefer** [UoA-eResearch/openface_mass_compare#3]
After running the new image, I get the exceptions below, resulting in a stopped container.
I'm running on Windows with Docker 1.12  Quickstart Terminal, maybe the mounting is a problem?

```
2017-02-01T21:49:12.672950336Z [2017-02-01 21:49:12 +0000] [24] [ERROR] Exception in worker process
2017-02-01T21:49:12.672961570Z Traceback (most recent call last):
2017-02-01T21:49:12.672964723Z   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
2017-02-01T21:49:12.672967468Z     worker.init_process()
2017-02-01T21:49:12.672969895Z   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
2017-02-01T21:49:12.672977429Z     self.load_wsgi()
2017-02-01T21:49:12.672979807Z   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
2017-02-01T21:49:12.672982091Z     self.wsgi = self.app.wsgi()
2017-02-01T21:49:12.672984242Z   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
2017-02-01T21:49:12.672986423Z     self.callable = self.load()
2017-02-01T21:49:12.672988468Z   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-02-01T21:49:12.672990588Z     return self.load_wsgiapp()
2017-02-01T21:49:12.672992487Z   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-02-01T21:49:12.672994724Z     return util.import_app(self.app_uri)
2017-02-01T21:49:12.672996763Z   File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
2017-02-01T21:49:12.672998886Z     __import__(module)
2017-02-01T21:49:12.673000850Z   File "/root/web_server.py", line 49, in <module>
2017-02-01T21:49:12.673003191Z     print("Unable to load data.json: " + e)
2017-02-01T21:49:12.673005300Z TypeError: cannot concatenate 'str' and 'exceptions.IOError' objects
2017-02-01T21:49:12.673157545Z [2017-02-01 21:49:12 +0000] [24] [INFO] Worker exiting (pid: 24)



```

**Comment by neon-ninja** [comment]
Issue appears to be caused by data.json not being present - but as I said in the readme data.json should be optional. https://github.com/UoA-eResearch/openface_mass_compare/commit/ae36ca31273134965c3b182beb946772ee18c51f should fix this issue, docker build here: https://hub.docker.com/r/uoacer/openface-mass-compare/builds/bcfrarsmyhufkxus63xmi9t/

Give that a try and see if that fixes your issue
Thanks for bug testing! 🐛

**Comment by geziefer** [comment]
Ok, that fix made it continue, allthough giving me a
`('Unable to load data.json: ', IOError(2, 'No such file or directory'))`
for each worker.
And the created pickle file is only 6 byte long.
I assume, that on Windows my directory, where the data of the images is in, does not get correctly mounted and thus, it cannot read the data.json, no matter if it's there or not and also no images.

I guess, you haven't tried it on Windows?

**Comment by neon-ninja** [comment]
Try remove the pickle file, and then restart the docker container. It should try regenerate it. Ensure you're mounting as per ```docker run --name=omc --restart=always --detach=true --volume="`pwd`:/root/data" --publish="8000:8000" --net=host uoacer/openface-mass-compare``` where \`pwd\` is the directory you have your images in - you may need to replace this if you're not running this via bash (via, cygwin, git bash, or ubuntu on windows) / if you don't have a pwd binary in your PATH

Nope, I've only tested this on Ubuntu

**Comment by geziefer** [comment]
It works when I execute it directly from docker-machine, so it really seems to be a Problem with Windows mounting the directory. Thanks!
