### ISSUE TITLE
 No such file or directory: '/root/data/data.pickle'

### ISSUE THREAD

**Issue by jorngeorg** [UoA-eResearch/openface_mass_compare#7]
I get this error when booting the docker. Seems it's unable to find data.pickle and is unable to create a new one? 

```
[2017-09-14 08:35:40 +0000] [27] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/root/web_server.py", line 24, in <module>
    from util import *
  File "/root/util.py", line 23, in <module>
    with open("/root/data/data.pickle") as f:
IOError: [Errno 2] No such file or directory: '/root/data/data.pickle'
```

**Comment by neon-ninja** [comment]
There would have been an error earlier on (in generate_pickle.py) that is causing this issue - scroll up in your logs. Hard to say what the issue is without seeing the root cause, but possibly you don't have permissions to write in the directory you mounted? Normally docker is run as root, but I know by adding yourself to the docker group you can do things as a normal user

**Comment by jorngeorg** [comment]
Thanks for getting back.

This is the full stack trace: 
```
sudo docker run --rm --volume $(PWD):/root/data  --publish="8000:8000" --net=host --name=omc uoacer/openface-mass-compare 

generating pickle
Traceback (most recent call last):
  File "generate_pickle.py", line 3, in <module>
    from util import *
  File "/root/util.py", line 23, in <module>
    with open("/root/data/data.pickle") as f:
IOError: [Errno 2] No such file or directory: '/root/data/data.pickle'
[2017-09-15 14:27:43 +0000] [20] [INFO] Starting gunicorn 19.7.1
[2017-09-15 14:27:43 +0000] [20] [INFO] Listening at: http://0.0.0.0:8000 (20)
[2017-09-15 14:27:43 +0000] [20] [INFO] Using worker: sync
[2017-09-15 14:27:43 +0000] [25] [INFO] Booting worker with pid: 25
[2017-09-15 14:27:43 +0000] [30] [INFO] Booting worker with pid: 30
[2017-09-15 14:27:43 +0000] [35] [INFO] Booting worker with pid: 35
[2017-09-15 14:27:43 +0000] [40] [INFO] Booting worker with pid: 40
[2017-09-15 14:27:43 +0000] [48] [INFO] Booting worker with pid: 48
[2017-09-15 14:27:43 +0000] [53] [INFO] Booting worker with pid: 53
[2017-09-15 14:27:43 +0000] [54] [INFO] Booting worker with pid: 54
[2017-09-15 14:27:43 +0000] [63] [INFO] Booting worker with pid: 63
[2017-09-15 14:27:46 +0000] [54] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/root/web_server.py", line 24, in <module>
    from util import *
  File "/root/util.py", line 23, in <module>
    with open("/root/data/data.pickle") as f:
IOError: [Errno 2] No such file or directory: '/root/data/data.pickle'
[2017-09-15 14:27:46 +0000] [54] [INFO] Worker exiting (pid: 54)
[2017-09-15 14:27:46 +0000] [25] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/root/web_server.py", line 24, in <module>
    from util import *
  File "/root/util.py", line 23, in <module>
    with open("/root/data/data.pickle") as f:
IOError: [Errno 2] No such file or directory: '/root/data/data.pickle'
[2017-09-15 14:27:46 +0000] [25] [INFO] Worker exiting (pid: 25)
[2017-09-15 14:27:46 +0000] [30] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/root/web_server.py", line 24, in <module>
    from util import *
  File "/root/util.py", line 23, in <module>
    with open("/root/data/data.pickle") as f:
IOError: [Errno 2] No such file or directory: '/root/data/data.pickle'
[2017-09-15 14:27:46 +0000] [30] [INFO] Worker exiting (pid: 30)
[2017-09-15 14:27:46 +0000] [48] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/root/web_server.py", line 24, in <module>
    from util import *
  File "/root/util.py", line 23, in <module>
    with open("/root/data/data.pickle") as f:
IOError: [Errno 2] No such file or directory: '/root/data/data.pickle'
[2017-09-15 14:27:46 +0000] [48] [INFO] Worker exiting (pid: 48)
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 231, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

I don't think it is a permission issue since i am able to do this

```
docker run --rm --volume $(PWD):/root/data uoacer/openface-mass-compare touch /root/data/data.pickle  
```

**Comment by neon-ninja** [comment]
Ok, this is my fault. I've inadvertently caused this bug with commit https://github.com/UoA-eResearch/openface_mass_compare/commit/19337dcc8df31c3e3b8e1ff42eb2eda1d90e0a09, and since I already had a generated pickle file it didn't occur for me during testing. Please try with an earlier version using the command `docker pull uoacer/openface-mass-compare:1.04`

**Comment by jorngeorg** [comment]
Yes, thanks that works!

**Comment by neon-ninja** [comment]
https://github.com/UoA-eResearch/openface_mass_compare/commit/76c266f5bf66426963e6fec5d3bb0efced4e64d8 fixes this issue :)
